apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: multiarch-native-buildah-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multiarch-native-buildah-pipeline
subjects:
  - kind: ServiceAccount
    name: pipeline
